version: '3.8'
services:

  # Docker connection string for local machine: postgres://postgres:postgres@localhost:5432/

  postgres:
    image: postgres:13.5
    restart: always
    environment:           
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:               
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'        

volumes:
  postgres: